# Generated by Django 4.2.7 on 2023-12-19 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aviary',
            name='winter_place',
            field=models.BooleanField(default=False),
        ),
    ]
